# build stage
FROM --platform=linux/amd64 node:21-alpine AS dev
WORKDIR /frontend
COPY package.json ./
RUN npm install
COPY . .


FROM --platform=linux/amd64 node:21-alpine AS build
WORKDIR /frontend

COPY --from=dev /frontend/node_modules /frontend/node_modules
COPY . .

RUN npm run build

FROM nginx:alpine AS production

COPY --from=build /frontend/dist /usr/share/nginx/html