version: "1"
name: ebikecity
services:
  vue:
    container_name: frontend-server
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    networks:
      - fullstack-network
    volumes:
      - ./frontend:/frontend

  flask:
    container_name: backend-server
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8989:8989"
    networks:
      - fullstack-network
    volumes:
      - ./backend:/backend
networks:
  fullstack-network:
    driver: bridge
